"""add user registration fields

Revision ID: 6a12afa86133
Revises: f5f08316ea8d
Create Date: 2026-04-17 11:55:50.276004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a12afa86133'
down_revision: Union[str, None] = 'f5f08316ea8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('department', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('status', sa.String(length=30), nullable=False))
    op.alter_column('users', 'employee_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_index('ix_users_name', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_name', 'users', ['name'], unique=False)
    op.alter_column('users', 'employee_id',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('users', 'status')
    op.drop_column('users', 'department')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
