"""create_attendances_table

Revision ID: f8adf47d8f9d
Revises: 6a12afa86133
Create Date: 2026-04-17 15:26:04.377329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8adf47d8f9d'
down_revision: Union[str, None] = '6a12afa86133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('employee_id', sa.String(), nullable=False))
    op.add_column('attendances', sa.Column('timestamp', sa.DateTime(), nullable=False))
    op.drop_index('ix_attendances_id', table_name='attendances')
    op.drop_index('ix_attendances_session_id', table_name='attendances')
    op.drop_index('ix_attendances_user_id', table_name='attendances')
    op.drop_constraint('attendances_session_id_fkey', 'attendances', type_='foreignkey')
    op.drop_constraint('attendances_user_id_fkey', 'attendances', type_='foreignkey')
    op.create_foreign_key(None, 'attendances', 'users', ['employee_id'], ['employee_id'])
    op.drop_column('attendances', 'check_out_time')
    op.drop_column('attendances', 'user_id')
    op.drop_column('attendances', 'session_id')
    op.drop_column('attendances', 'check_in_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('check_in_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('attendances', sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('attendances', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('attendances', sa.Column('check_out_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.create_foreign_key('attendances_user_id_fkey', 'attendances', 'users', ['user_id'], ['id'])
    op.create_foreign_key('attendances_session_id_fkey', 'attendances', 'sessions', ['session_id'], ['id'])
    op.create_index('ix_attendances_user_id', 'attendances', ['user_id'], unique=False)
    op.create_index('ix_attendances_session_id', 'attendances', ['session_id'], unique=False)
    op.create_index('ix_attendances_id', 'attendances', ['id'], unique=False)
    op.drop_column('attendances', 'timestamp')
    op.drop_column('attendances', 'employee_id')
    # ### end Alembic commands ###
